import type { Metadata } from "next";
import { playfair_display, quicksand } from "./ui/fonts";
import "./ui/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair_display.variable} ${quicksand.variable} antialiased`}>{children}</body>
    </html>
  );
}
