const projectList = [
   {
      name: 'Countries API Dashboard',
      id: 'countries_dashboard',
      img: '/img/countries_dashboard.png',
      stack: [
         'JavaScript',
         'React',
         'Gatsby',
         'MUI',
         'Restful API integration',
         'AWS',
      ],
      url: 'https://main.d8wbp4tt7l3hc.amplifyapp.com/',
   },
   {
      name: 'Authentication Funnel (Sign Up | Login) w/ Image upload',
      id: 'auth_funnel',
      img: '/img/auth_funnel.png',
      stack: [
         'AWS-SDK',
         'AWS-S3',
         'AWS-Lambda',
         'AWS-Cognito',
         'AWS-IAM',
         'AWS-Amplify',
         'JavaScript',
         'React',
         'Gatsby',
         'MUI',
      ],
      url: 'https://main.d3t8egz5y9i39c.amplifyapp.com/',
   },
   //  {
   //     name: 'Redux & React SPA w/ Rest API Integration',
   //     id: 'redux_spa',
   //     img: '/img/redux_spa.png',
   //     stack: ['JavaScript', 'React', 'Redux', 'MUI'],
   //     url: 'https://kirill-develops.github.io/react-redux-axios-spa/',
   //  },
   //  {
   //     name: 'InStock',
   //     id: 'in_stock',
   //     img: '/img/InStock.jpg',
   //     stack: [
   //        'JavaScript',
   //        'React',
   //        'Router',
   //        'React Lifecycle Methods',
   //        'Axios',
   //        'Sass',
   //     ],
   //     url: 'https://kirills-instock.herokuapp.com/warehouses',
   //  },
   // {
   //    name: 'BrainFlix',
   //    id: 'brain_flix',
   //    img: '/img/brainFlix2.png',
   //    stack: [
   //       'JavaScript',
   //       'React',
   //       'React Router',
   //       'React Lifecycle Methods',
   //       'Axios',
   //       'Heroku',
   //    ],
   //    url: 'https://kirills-brainflix.herokuapp.com/',
   // },
   {
      name: 'BandSite',
      id: 'band_site',
      img: '/img/bandSite2.png',
      stack: [
         'JavaScript',
         'JQuery',
         'Axios',
         'HTML5',
         'Sass/CSS3',
         'Git',
         'Figma',
      ],
      url: 'https://kirill-develops.github.io/bandSite/',
   },
   {
      name: 'TravelSite',
      id: 'travel_site',
      img: '/img/travelSite2.png',
      stack: ['HTML5', 'Sass/CSS3', 'BEM', 'GH-Pages'],
      url: 'https://kirill-develops.github.io/travelSite/',
   },
   {
      name: 'Nitro Coffee',
      id: 'nitro_coffee',
      img: '/img/coffeeShop2.png',
      stack: ['HTML5', 'Sass/CSS3', 'BEM', 'GH-Pages'],
      url: 'https://kirill-develops.github.io/coffeeShop/',
   },
   //  {
   //     name: 'Lost & Found',
   //     id: 'lost_and_found',
   //     img: '/img/lostAndFound.png',
   //     stack: ['JavaScript', 'React.js', 'Hooks', 'Router', 'Axios'],
   //     url: 'https://lostnfound.netlify.app/',
   //  },
];

export default projectList;
